Refac/cas 210 message entity
GetStream/stream-chat-android-livedata pull request #71
Opened 2020-10-12 09:27 UTC by ogkuzmin

WIP. Not ready for review
[CAS-210](https://stream-io.atlassian.net/secure/RapidBoard.jspa?rapidView=49&projectKey=CAS&modal=detail&selectedIssue=CAS-210)

### Description

Reface repo layer for Messages. Making MessageEntity inner library model, hide from public API.

### Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [ ] Changelog updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Reviewers added

2020-10-14 07:06 UTC, ogkuzmin commented on livedata/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt
> -                    entity.sendMessageCompletedAt = Date()
Check it

2020-10-16 18:50 UTC, tschellenbach requested changes
There is a performance regression on the flow for querying channels.

2020-10-16 18:50 UTC, tschellenbach commented on livedata/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
aren't you hitting the database twice with this setup?

2020-10-16 18:50 UTC, tschellenbach commented on livedata/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
once here and then a few lines later with selectMessagesForChannel

2020-10-19 10:34 UTC, ogkuzmin reviewed
Moved quarrying and entity selection to helper. It required create RepositoryFactory (for test purpose). Added tests for that method.

2020-10-19 14:07 UTC, JcMinarro approved these changes
LGTM

2020-10-20 07:23 UTC, adasiewiczr approved these changes

2020-10-20 10:59 UTC, merged